import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Learn Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1 className="text-2xl font-bold text-center mt-5">Hello Shiv Srivastava</h1>
      <Link className="flex justify-center underline" href="/posts" >Go to Posts</Link>
      </main>
    </>
  )
}

